Add benchmark tests
chipmunk-project/druzhba pull request #10
Opened 2019-10-04 15:45 UTC by mdw362

2019-10-04 16:10 UTC, anirudhSK approved these changes

2019-10-04 16:11 UTC, anirudhSK requested changes
This looks good. Can we add the benchmarks to appveyor.yml so that they are run on every commit? Will allow us to detect performance regressions.

2019-10-04 16:56 UTC, mdw362 commented
The benchmarks failed to run. I'm looking into it and will make another commit when it's fixed

2019-10-05 00:45 UTC, mdw362 commented
Does this look good to merge?

2019-10-05 01:29 UTC, anirudhSK approved these changes

2019-10-05 01:30 UTC, merged